
seuratBootstrap <- function(group=c("sudo","docker"), scratch.folder, file, nPerm, permAtTime, percent, separator, logTen=0, pcaDimensions, seed=111,sparse=FALSE,format="NULL",resolution=0.6, isNormalized=FALSE, variableFeatures=NULL){

  if(!sparse){
    seuratPermutation(group=group, scratch.folder=scratch.folder, file=file, nPerm=nPerm, permAtTime=permAtTime, percent=percent, separator=separator, logTen=logTen, pcaDimensions=pcaDimensions, seed=seed, sparse=sparse,resolution=resolution,isNormalized=isNormalized, variableFeatures=variableFeatures)
    cluster.path <- paste(data.folder=dirname(file), "Results", strsplit(basename(file),"\\.")[[1]][1], sep="/")
    cluster <- as.numeric(list.dirs(cluster.path, full.names = FALSE, recursive = FALSE))
  #if(length(cluster)==1){
  #  permAnalysisSeurat(group=group, scratch.folder=scratch.folder,file=file, nCluster=cluster, separator=separator, sp=0.8)
  #} else{
  # cat("\nIt seems that there is more than one cluster folders in the output of seuratPermutation\n")
  #  cat("Check the results generated by seuratPermutation, and run permAnalysisSeurat selecting the cluster of interest\n")
  #  system("echo 5 > ExitStatusFile 2>&1")
  #  return(5)
  #}
    
  }else{
  
    seuratPermutation(group=group, scratch.folder=scratch.folder, file=file, nPerm=nPerm, permAtTime=permAtTime, percent=percent, separator=separator, logTen=logTen, pcaDimensions=pcaDimensions, seed=seed,sparse=sparse,format=format,resolution=resolution,isNormalized=isNormalized, variableFeatures=variableFeatures)
   matrixName=strsplit(dirname(file),"/")[[1]][length(strsplit(dirname(file),"/")[[1]])]
   data.folder=paste(strsplit(dirname(file),"/")[[1]][-length(strsplit(dirname(file),"/")[[1]])],collapse="/")
   cluster.path <- paste(data.folder=data.folder, "Results",strsplit(dirname(file),"/")[[1]][length(strsplit(dirname(file),"/")[[1]])], sep="/")
    
    

    cluster <- as.numeric(list.dirs(cluster.path, full.names = FALSE, recursive = FALSE))
  #if(length(cluster)==1){
  #  permAnalysisSeurat(group=group, scratch.folder=scratch.folder,file=file, nCluster=cluster, separator=separator, sp=0.8,sparse=sparse,format=format)
  #} else{
  #  cat("\nIt seems that there is more than one cluster folders in the output of seuratPermutation\n")
  #  cat("Check the results generated by seuratPermutation, and run permAnalysisSeurat selecting the cluster of interest\n")
  #  system("echo 5 > ExitStatusFile 2>&1")
  #  return(5)
  #}
  
  
  
  
  
  
  
  }

}



seuratPermutation <- function(group=c("sudo","docker"), scratch.folder, file, nPerm, permAtTime, percent, separator, logTen=0,pcaDimensions,seed=1111,sparse=FALSE,format="NULL",resolution=0.6, isNormalized=FALSE, variableFeatures=NULL){

if(!sparse){
  data.folder=dirname(file)
positions=length(strsplit(basename(file),"\\.")[[1]])
matrixNameC=strsplit(basename(file),"\\.")[[1]]
matrixName=paste(matrixNameC[seq(1,positions-1)],collapse="")
format=strsplit(basename(basename(file)),"\\.")[[1]][positions]
}else{
  matrixName=strsplit(dirname(file),"/")[[1]][length(strsplit(dirname(file),"/")[[1]])]
  data.folder=paste(strsplit(dirname(file),"/")[[1]][-length(strsplit(dirname(file),"/")[[1]])],collapse="/")
  if(format=="NULL"){
  stop("Format output cannot be NULL for sparse matrix")
  }
}

  #running time 1
  ptm <- proc.time()
  #setting the data.folder as working folder
  if (!file.exists(data.folder)){
    cat(paste("\nIt seems that the ",data.folder, " folder does not exist\n"))
    system("echo 2 > ExitStatusFile 2>&1")
    return(2)
  }

  #storing the position of the home folder
  home <- getwd()
  setwd(data.folder)
  #initialize status
  system("echo 0 > ExitStatusFile 2>&1")

  #testing if docker is running
  test <- dockerTest()
  if(!test){
    cat("\nERROR: Docker seems not to be installed in your system\n")
    system("echo 10 > ExitStatusFile 2>&1")
    setwd(home)
    return(10)
  }



  #check  if scratch folder exist
  if (!file.exists(scratch.folder)){
    cat(paste("\nIt seems that the ",scratch.folder, " folder does not exist\n"))
    system("echo 3 > ExitStatusFile 2>&1")
    setwd(data.folder)
    return(3)
  }
  tmp.folder <- gsub(":","-",gsub(" ","-",date()))
  scrat_tmp.folder=file.path(scratch.folder, tmp.folder)
  writeLines(scrat_tmp.folder,paste(data.folder,"/tempFolderID", sep=""))
  cat("\ncreating a folder in scratch folder\n")
  dir.create(file.path(scrat_tmp.folder))
  #preprocess matrix and copying files

if(separator=="\t"){
separator="tab"
}

 dir.create(paste(scrat_tmp.folder,"/",matrixName,sep=""))
 dir.create(paste(data.folder,"/Results",sep=""))
 if(sparse==FALSE){
system(paste("cp ",data.folder,"/",matrixName,".",format," ",scrat_tmp.folder,"/",sep=""))
varFeat_rebuild <- gsub('_cellCycleScaleData', '_variableFeatures.txt', matrixName, fixed=TRUE)
system(paste("cp ",data.folder,"/",varFeat_rebuild," ",scrat_tmp.folder,"/",sep="")) 
# TODO basename variableFeatures would be better, but need to be able to do so also inside docker
print(paste("cp ",data.folder,"/",varFeat_rebuild," ",scrat_tmp.folder,"/",sep=""))
}else{
system(paste("cp -r ",data.folder,"/",matrixName,"/ ",scrat_tmp.folder,"/",sep=""))

}

  #executing the docker job
  if (is.null(variableFeatures)) {
    variableFeatures="NULL"
  }
    params <- paste("--cidfile ",data.folder,"/dockerID -v ",scrat_tmp.folder,":/scratch -v ", data.folder, ":/data -d seuratpermutation_savewithres_loadscaleddata Rscript /home/main.R ",matrixName," ",nPerm," ",permAtTime," ",percent," ",format," ",separator," ",logTen," ",pcaDimensions," ",seed," ",sparse," ",resolution," ", isNormalized, " ", variableFeatures,  sep="")
print('DOCKER params:')
print(params)
resultRun <- runDocker(group=group, params=params)

  #waiting for the end of the container work
  if(resultRun==0){
    #system(paste("cp ", scrat_tmp.folder, "/* ", data.folder, sep=""))
  }
  #running time 2
  ptm <- proc.time() - ptm
  dir <- dir(data.folder)
  dir <- dir[grep("run.info",dir)]
  if(length(dir)>0){
    con <- file("run.info", "r")
    tmp.run <- readLines(con)
    close(con)
    tmp.run[length(tmp.run)+1] <- paste("user run time mins ",ptm[1]/60, sep="")
    tmp.run[length(tmp.run)+1] <- paste("system run time mins ",ptm[2]/60, sep="")
    tmp.run[length(tmp.run)+1] <- paste("elapsed run time mins ",ptm[3]/60, sep="")
    writeLines(tmp.run,"run.info")
  }else{
    tmp.run <- NULL
    tmp.run[1] <- paste("run time mins ",ptm[1]/60, sep="")
    tmp.run[length(tmp.run)+1] <- paste("system run time mins ",ptm[2]/60, sep="")
    tmp.run[length(tmp.run)+1] <- paste("elapsed run time mins ",ptm[3]/60, sep="")

    writeLines(tmp.run,"run.info")
  }

  #saving log and removing docker container
  container.id <- readLines(paste(data.folder,"/dockerID", sep=""), warn = FALSE)
  system(paste("docker logs ", substr(container.id,1,12), " &> ",data.folder,"/", substr(container.id,1,12),".log", sep=""))
  system(paste("docker rm ", container.id, sep=""))


  #Copy result folder
  cat("Copying Result Folder")
  system(paste("cp -r ",scrat_tmp.folder,"/* ",data.folder,"/Results",sep=""))
  #removing temporary folder
  cat("\n\nRemoving the temporary file ....\n")
  system(paste("rm -R ",scrat_tmp.folder))
  system("rm -fR out.info")
  system("rm -fR dockerID")
  system("rm  -fR tempFolderID")
  system(paste("cp ",paste(path.package(package="rCASC"),"containers/containers.txt",sep="/")," ",data.folder, sep=""))
  setwd(home)
}


# If needed also get https://github.com/kendomaniac/rCASC/blob/master/R/permAnalysisSeurat.R and local copy of  docker.io/repbioinfo/seuratanalysis