import os
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,'.PRJ_ROOT')):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception('Can not find the PRJ_ROOT directory')

PRJ_ROOT=find_prj_root()
BIOINFO_ROOT = os.getenv('BIOINFO_ROOT')
SNAKE_ROOT=os.getenv('SNAKE_ROOT')

BIN_DIR=PRJ_ROOT+'/local/bin'
SRC_DIR=PRJ_ROOT+'/local/src'

CSV_DIR='/mnt/cold1/snaketree/prj/scRNA/dataset/Scanpy_prova/count_matrix/GSE132465'
RCASC_GTF=PRJ_ROOT+"/local/share/data/Homo_sapiens.GRCh38.101.gtf"

# do we choose randomly one ensg for the bad gene symbol with more than one ensg and translate saver outputs?
rule ensg_gs_map:
    input: gtf=RCASC_GTF
    output: map="ensg_gs_map.tsv", map_disamb="first_ensg_gs_map.tsv"
    script: SRC_DIR+"/gtf_to_map.R"

MAP="first_ensg_gs_map.tsv"

rule removefirstcol_copycsv:
    input: counts=CSV_DIR+'/GSE132465_GEO_processed_CRC_10X_raw_UMI_{sample}_count_matrix_epithelial.csv', gtf=RCASC_GTF, map=MAP
    output: counts="{sample}_dir/{sample}.csv", gtf="{sample}_dir/gtf.gtf"
    params: dir="{sample}_dir"
    shell:  
        """
            mkdir -p {params.dir}
            cp {input.gtf} {output.gtf}
            tr "," "\\t" < {input.counts} |  tee >(bawk 'NR==1' | tr "\\t" "," > {output.counts}.tmp2) | translate -k {input.map} 1 | tr "\\t" "," > {output.counts}.tmp
            cat {output.counts}.tmp2 {output.counts}.tmp > {output.counts}
            rm {output.counts}.tmp*
        """

SAMPLES=["SMC01-N","SMC01-T","SMC02-N","SMC02-T","SMC03-N","SMC03-T","SMC04-N","SMC04-T","SMC05-N","SMC06-N","SMC06-T","SMC07-N","SMC07-T","SMC08-N","SMC08-T","SMC09-N","SMC09-T","SMC10-N","SMC10-T","SMC11-T","SMC14-T","SMC15-T","SMC16-T","SMC17-T","SMC18-T","SMC19-T","SMC20-T","SMC21-T","SMC22-T","SMC23-T","SMC24-T","SMC25-T"]
#SAMPLES=["SMC01-N","SMC01-T","SMC02-N","SMC02-T","SMC03-N","SMC03-T","SMC04-N","SMC04-T","SMC05-N","SMC05-T","SMC06-N","SMC06-T","SMC07-N","SMC07-T","SMC08-N","SMC08-T","SMC09-N","SMC09-T","SMC10-N","SMC10-T","SMC11-T","SMC14-T","SMC15-T","SMC16-T","SMC17-T","SMC18-T","SMC19-T","SMC20-T","SMC21-T","SMC22-T","SMC23-T","SMC24-T","SMC25-T"]
#SAMPLES=["SMC01-N","SMC01-T","SMC02-N","SMC02-T","SMC03-N","SMC04-N","SMC05-N","SMC06-N","SMC07-N","SMC07-T","SMC08-N","SMC09-T","SMC10-N","SMC10-T","SMC11-T","SMC14-T","SMC15-T","SMC16-T","SMC17-T","SMC19-T","SMC20-T","SMC21-T","SMC23-T","SMC24-T"]


NSAMPLES=len(SAMPLES)

BASED='/mnt/cold1/snaketree/prj/scRNA/dataset/Scanpy_prova'

ALL_CSV=expand(CSV_DIR+'/{sample}.tsv', sample=SAMPLES)
CORES=10

SCRATCH="/tmp"

VIO_GENES='/mnt/cold1/snaketree/prj/scRNA/local/share/data/Ire_cetuxi_first_and_reseq/genes_ensg.tsv'
CYCLE_GENES='/mnt/cold1/snaketree/prj/scRNA/local/share/data/Ire_cetuxi_first_and_reseq/regev_lab_cell_cycle_genes_onlyensg.txt'


#BASE_DIR_RAF='/mnt/cold1/calogero/reanalysis_on_AIsc/paneth_only/time_course/'
SAMPLES_MAP_RAF= {
}
