DEBUG="yes"
PRJ_ROOT="../../"
SRC_DIR=PRJ_ROOT+"local/src/"
#CLUSTER=
CRIS=PRJ_ROOT+"local/share/data/cris_wanted_gs.tsv"

TRANSCRIPTOME=PRJ_ROOT+"local/share/data/refdata-cellranger-GRCh38-1.2.0"
# TODO redo with wget http://cf.10xgenomics.com/supp/cell-exp/refdata-cellranger-GRCh38-3.0.0.tar.gz
MEM=90
#CORES=8
CORES=12 # upped for velocyto
CELLRANGER=PRJ_ROOT+"local/src/cellranger-3.1.0/cellranger"
FASTQ_DIR='./HL7L3DRXY/outs/fastq_path/'
SEQ_DIR='/mnt/cold1/upload/scRNA_Candiolo_12_2021/ll/211209_A00959_0109_BHL7L3DRXY'

SAMPLES=[
"PDO_livermet_CRC0323_4d_NOEGF_3_NN",
"PDO_livermet_CRC0322_4d_EGF_3_NN",
"PDO_livermet_CRC0323_8d_NOEGF_3_NN",
"PDO_livermet_CRC0322_8d_EGF_3_NN",
"PDO_livermet_CRC0323_3d_CTX_3_NN",
"PDO_livermet_CRC0323_12d_NOEGF_3_NN",
"PDO_livermet_CRC0322_12d_EGF_3_NN",
"PDO_livermet_CRC0323_7d_CTX_3_NN"
]

OSAMPLES=[
"CRC0322_4d_NOEGF",
"CRC0322_4d_EGF",
"CRC0322_8d_NOEGF",
"CRC0322_8d_EGF",
"CRC0322_3d_CTX",
"CRC0322_12d_NOEGF",
"CRC0322_12d_EGF",
"CRC0322_7d_CTX"
]

NSAMPLES=len(SAMPLES)

#GSEA_PATHWAYS=PRJ_ROOT+"local/share/data/Hallmark_curated_hs_entred.RData"
#GSEA_PATHWAYS=PRJ_ROOT+"local/share/data/Hallmark_curated_hs_symbol.RData"
GSEA_PATHWAYS=PRJ_ROOT+"local/share/data/Curated_onco_hs_symbol.RData"
GSEA=PRJ_ROOT+"/local/src/gsea.R"
GSEA_INPUT=PRJ_ROOT+"/local/src/gsea_input_from_cr.R"
GSEA_XLS=PRJ_ROOT+"/local/src/gsea_genes_signature.R"

SEURAT_PARAMS=PRJ_ROOT+"local/share/data/seurat_params.txt"

SEURAT_MARKERS=SRC_DIR+"seurat_markers_pca.R"
SEURAT_VIOLIN=SRC_DIR+"seurat_violin.R"
VIOLIN_GENES='ATOH1,GFI1,SOX9,XBP1,DEFA5,DEFA6,LYZ,SPINK4,DLL1,DLL4'

RCASC_DIR=PRJ_ROOT+'/dataset/rCASC_timecourse' 


REPEATS="/mnt/trcanmed/temp/rmsk.gtf"

