import os
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,'.PRJ_ROOT')):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception('Can not find the PRJ_ROOT directory')

PRJ_ROOT=find_prj_root()
BIOINFO_ROOT = os.getenv('BIOINFO_ROOT')
SNAKE_ROOT=os.getenv('SNAKE_ROOT')

BIN_DIR=PRJ_ROOT+'/local/bin'
SRC_DIR=PRJ_ROOT+'/local/src'

SAMPLES=["CRC0327_NT_t1","CRC0327_NT_t2"]
NSAMPLES=len(SAMPLES)

CSV_DIR='/mnt/trcanmed/snaketree/prj/scRNA/dataset/sc_Ire_multipleconservation/'

ALL_CSV=expand(CSV_DIR+'/{sample}.csv', sample=SAMPLES)
CORES=10

RCASC_GTF="/mnt/cold1/calogero/reanalysis_on_AIsc/comparing_CRC0322/CRC0322_NT_1_bis_clx/Homo_sapiens.GRCh38.101.gtf"
SCRATCH="/tmp"

VIO_GENES='/mnt/cold1/snaketree/prj/scRNA/local/share/data/Ire_cetuxi_first_and_reseq/genes_ensg.tsv'
CYCLE_GENES='/mnt/cold1/snaketree/prj/scRNA/local/share/data/Ire_cetuxi_first_and_reseq/regev_lab_cell_cycle_genes_onlyensg.txt'
BASED='/mnt/cold1/snaketree/prj/scRNA/dataset/rCASC_IRCC_tecrep/'

SPEC='_mulcos'
rule all_seurat_integration:
    input: expand("{sample}_res{res}_G1_clu_cycle.tsv", res=[0.01, 0.05, 0.1, 0.2, 0.5], sample=["CRC0327"])

