DEBUG="yes"
PRJ_ROOT="/mnt/trcanmed/snaketree/prj/scRNA/"#TODO FIXME
SRC_DIR=PRJ_ROOT+"local/src/"
#CLUSTER=
CRIS=PRJ_ROOT+"local/share/data/cris_wanted_gs.tsv"

TRANSCRIPTOME=PRJ_ROOT+"local/share/data/refdata-cellranger-GRCh38-1.2.0"
# TODO redo with wget http://cf.10xgenomics.com/supp/cell-exp/refdata-cellranger-GRCh38-3.0.0.tar.gz
MEM=90
CORES=24
CELLRANGER=PRJ_ROOT+"local/src/cellranger-3.1.0/cellranger"
FASTQ_DIR=PRJ_ROOT+"local/share/data/sc_Ire_multipleconservation/raw/raw/"
SAMPLES=['IRC-BL-g007','IRC-BL-g008']
OSAMPLES=['CRC0327_NT72h_Vivophix','CRC0327_CTX72h_Vivophix']
NSAMPLES=len(SAMPLES)
#GSEA_PATHWAYS=PRJ_ROOT+"local/share/data/Hallmark_curated_hs_entred.RData"
#GSEA_PATHWAYS=PRJ_ROOT+"local/share/data/Hallmark_curated_hs_symbol.RData"
GSEA_PATHWAYS=PRJ_ROOT+"local/share/data/Curated_onco_hs_symbol.RData"
GSEA=PRJ_ROOT+"/local/src/gsea.R"
GSEA_INPUT=PRJ_ROOT+"/local/src/gsea_input_from_cr.R"
GSEA_XLS=PRJ_ROOT+"/local/src/gsea_genes_signature.R"

SEURAT_PARAMS=PRJ_ROOT+"local/share/data/seurat_params.txt"
