DEBUG="yes"
PRJ_ROOT="../../"
SRC_DIR=PRJ_ROOT+"local/src/"
#CLUSTER=
CRIS=PRJ_ROOT+"local/share/data/cris_wanted_gs.tsv"

TRANSCRIPTOME=PRJ_ROOT+"local/share/data/refdata-cellranger-GRCh38-1.2.0"
# TODO redo with wget http://cf.10xgenomics.com/supp/cell-exp/refdata-cellranger-GRCh38-3.0.0.tar.gz
MEM=90
CORES=24
CELLRANGER=PRJ_ROOT+"local/src/cellranger-3.1.0/cellranger"
FASTQ_DIR=PRJ_ROOT+"local/share/data/ire_cetuxi/ln_fq/"
SAMPLES=["Sample_S26093_499","Sample_S26094_500","Sample_S26095_501","Sample_S26096_502","Sample_S26369_503","Sample_S26370_504","Sample_S26371_505","Sample_S26371_506"]
OSAMPLES=["CRC0327_NT_1", "CRC0327_cetux_1", "CRC0322_NT_1", "CRC0322_cetux_1", "CRC0327_NT_2", "CRC0327_cetux_2", "CRC1502_NT_1", "CRC1502_cetux_1"]
NSAMPLES=len(SAMPLES)
#GSEA_PATHWAYS=PRJ_ROOT+"local/share/data/Hallmark_curated_hs_entred.RData"
#GSEA_PATHWAYS=PRJ_ROOT+"local/share/data/Hallmark_curated_hs_symbol.RData"
GSEA_PATHWAYS=PRJ_ROOT+"local/share/data/Curated_onco_hs_symbol.RData"
GSEA=PRJ_ROOT+"/local/src/gsea.R"
GSEA_INPUT=PRJ_ROOT+"/local/src/gsea_input_from_cr.R"
GSEA_XLS=PRJ_ROOT+"/local/src/gsea_genes_signature.R"

SEURAT_PARAMS=PRJ_ROOT+"local/share/data/seurat_params.txt"

SEURAT_MARKERS=SRC_DIR+"seurat_markers_pca.R"
SEURAT_MARKERS_NOCC=SRC_DIR+"seurat_markers_pca_nocc.R"
SEURAT_VIOLIN=SRC_DIR+"seurat_violin.R"
VIOLIN_GENES='ATOH1,GFI1,SOX9,XBP1,DEFA5,DEFA6,LYZ,SPINK4,DLL1,DLL4'

REPEATS="/mnt/bioionfotree/task/gencode/dataset/hsapiens/33/rmsk.gtf"
